SHADOW_MAP_SIZE = 1024

""" Camera constants """
CAM_TRACK_SENSITIVITY = 0.002
CAM_TUMBLE_SENSITIVITY = 0.002
CAM_ZOOM_SENSITIVITY = 0.05
CAM_DOLLY_SENSITIVITY = 0.2

""" Text constants """
TEXT_RESOLUTION = 64

""" Length conversion """
INCH_TO_METER = 0.0254